### ISSUE TITLE
ember+ Set Value Real from Variable

### ISSUE THREAD

**Issue by Bart-SL** [bitfocus/companion-module-generic-emberplus#45]
As setting ember+ values from variable is a great feature I guess enabling Set Value Real from Variable would be needed and helpful as well.
I use ember+ for Lawo PowerCores and Vistool software control and there are some Real parameters which would be nice to feed from custom variables.
Huge thanks!

**Comment by phillipivan** [comment]
Please try the attached version. You will need to use the 3.5 Beta due to updated dependencies.
In addition to the Set Real From Variable, please also check I haven't broken other actions, as there is some refactoring. I have also added a Set Boolean from Variable action, and a Parameter Equals True feedback.
These changes have not been tested beyond checking that it builds.

[companion-module-generic-emberplus_2.5.0.zip](https://github.com/user-attachments/files/17376689/companion-module-generic-emberplus_2.5.0.zip)

**Comment by Bart-SL** [comment]
Wow!
Sounds great and works great so far!
I'll keep testing it. Thank you!!!

**Comment by phillipivan** [comment]
Good to hear. It would be really helpful if you can retest all the set value actions to verify I didn't break anything.

**Comment by phillipivan** [comment]
Bart, Have you been able to test this any further?

**Comment by Bart-SL** [comment]
Yes indeed.  I&#39;m testing it and I cannot see any problems so far. I use two-way communication so &#34;Parameter Equals True&#34; works properly too. Thank you!  I&#39;ve tried it with StreamDeck XL and StreamDeck+ with Rotary functions.  
     
      
       
        Dnia 20 października 2024 22:03 phillipivan ***@***.***&gt; napisał(a):
       
    
       
         
 Bart, Have you been able to test this any further?

**Comment by phillipivan** [comment]
Resolved in 2.5.0
